milestone 1: process of creating your portfolio website
banlon-jones/portfolio pull request #1
Opened 2021-11-24 22:11 UTC by banlon-jones

# Creating my portfolio website
in the process of creating my portfolio website i
- added HTML and CSS linter. 
- added .gitignore file.
- added the index.html file.
- added styles.css stylesheet.
- added images and icons in the images folder.
- develop the portfolio header(navbar).
- develop the portfolio headline section.

2021-11-24 23:34 UTC, keneogu requested changes
Hi @banlon-jones , 

Good job so far!
The linters works fine.
Pull request has a descriptive title.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Move the logo out of the nav tag

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-11-24 23:34 UTC, keneogu commented on index.html
> +                </div>
The logo should also be a link... you can make it a link by using the `<a>` tag

2021-11-24 23:34 UTC, keneogu commented on index.html
> +                </article>
This is a paragraph. Make use of the `<p>` tag instead of the article semantic tag.

2021-11-24 23:34 UTC, keneogu commented on index.html
> +            </section>
Use the `<ul>` tag to group the list of icons and `<li>` per each icon not <div> tag. Each icon should be a link: you can make it a link by using the `<a>` tag.

2021-11-25 00:52 UTC, rotimiazeez requested changes
# Hi @banlon-jones 👋, 

### Great work on making the changes requested by a previous reviewer 👏 
1[](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 00:52 UTC, rotimiazeez commented on index.html
> +            </ul>
- [ ] Kindly make sure the icons are well aligned as seen in the original template😉✌
- Figma design
![screenshot (3)](https://user-images.githubusercontent.com/44624138/143332077-9791a578-b9ae-4d5b-a965-7e353a12db5e.png)
- Your design
![local design](https://user-images.githubusercontent.com/44624138/143332293-c8df1a92-cd23-407a-ade2-d461f25bf778.jpg)

2021-11-25 01:24 UTC, VanessaAoki approved these changes
## STATUS: APPROVED 🟢 
Hi @banlon-jones, 

Great job implementing all the changes required by the previous Code Reviewer, your project is complete! There is nothing else to say other than... it's time to merge it! 
Congratulations! 🎉 

<img alt="approved" src="https://64.media.tumblr.com/87e0b6469c957bf896cdec1cab646acf/tumblr_inline_pk1bdakCCp1rpcr9a_500.gif">

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 


Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 01:34 UTC, merged